import fs from 'node:fs/promises';
import path from 'node:path';

export async function buildBundleScripts({ bundleDir, targetKey, projectType, preassembledRepoIncluded, preassembledRepoEmbedsDependencies }) {
  const preassembledSection = preassembledRepoIncluded
    ? [
        'PREASSEMBLED_REPO_TAR="$ROOT_DIR/repo.tar.gz"',
        `PREASSEMBLED_REPO_EMBEDS_DEPENDENCIES="${preassembledRepoEmbedsDependencies ? '1' : '0'}"`,
        '',
        'extract_preassembled_repo() {',
        '  tar -xzf "$PREASSEMBLED_REPO_TAR" -C "$STAGE_ROOT"',
        '  if [[ ! -d "$STAGE_DIR" ]]; then',
        '    echo "Preassembled archive is missing top-level repo/: $PREASSEMBLED_REPO_TAR" >&2',
        '    return 1',
        '  fi',
        '}',
        '',
        'if [[ -f "$PREASSEMBLED_REPO_TAR" ]]; then',
        '  echo "Extracting preassembled repository into staged output for $OUT_DIR"',
        '  extract_preassembled_repo',
        '  USED_PREASSEMBLED_REPO="1"',
        'fi',
        ''
      ].join('\n')
    : '';

  const assembleScript = [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    'ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
    'OUT_DIR_INPUT="${1:-$ROOT_DIR/repo}"',
    'mkdir -p "$(dirname "$OUT_DIR_INPUT")"',
    'OUT_DIR_PARENT="$(cd "$(dirname "$OUT_DIR_INPUT")" && pwd)"',
    'OUT_DIR="$OUT_DIR_PARENT/$(basename "$OUT_DIR_INPUT")"',
    `TARGET_KEY="\${LLM_CONTEXT_TARGET:-${targetKey}}"`,
    'TARGET_DIR="$ROOT_DIR/targets/$TARGET_KEY"',
    'SOURCE_TAR="$ROOT_DIR/LLM_CONTEXT_source.tar.gz"',
    `DEPENDENCY_TAR="$TARGET_DIR/${projectType.dependencyArchiveFileName}"`,
    `TARGET_LOCK="$TARGET_DIR/${projectType.lockfileName}"`,
    'STAGE_ROOT="$(mktemp -d "$OUT_DIR_PARENT/.llm-context-assemble-XXXXXX")"',
    'STAGE_DIR="$STAGE_ROOT/repo"',
    'BACKUP_ROOT=""',
    'BACKUP_PATH=""',
    'USED_PREASSEMBLED_REPO="0"',
    'PREASSEMBLED_REPO_EMBEDS_DEPENDENCIES="0"',
    '',
    'cleanup() {',
    '  local status=$?',
    '  if [[ $status -ne 0 && -n "$BACKUP_PATH" && -e "$BACKUP_PATH" && ! -e "$OUT_DIR" ]]; then',
    '    mv "$BACKUP_PATH" "$OUT_DIR"',
    '    echo "Assembly failed; restored previous output at $OUT_DIR" >&2',
    '  fi',
    '  if [[ -n "$BACKUP_ROOT" && -e "$BACKUP_ROOT" ]]; then',
    '    rm -rf "$BACKUP_ROOT"',
    '  fi',
    '  if [[ -n "$STAGE_ROOT" && -e "$STAGE_ROOT" ]]; then',
    '    rm -rf "$STAGE_ROOT"',
    '  fi',
    '}',
    'trap cleanup EXIT',
    '',
    preassembledSection,
    'if [[ "$USED_PREASSEMBLED_REPO" != "1" ]]; then',
    '  echo "Extracting source snapshot into staged output for $OUT_DIR"',
    '  mkdir -p "$STAGE_DIR"',
    '  tar -xzf "$SOURCE_TAR" -C "$STAGE_DIR"',
    '',
    `  SOURCE_LOCK="$STAGE_DIR/${projectType.lockfileName}"`,
    '  if [[ -f "$TARGET_LOCK" ]]; then',
    '    if [[ ! -f "$SOURCE_LOCK" ]]; then',
    '      cp "$TARGET_LOCK" "$SOURCE_LOCK"',
    `      echo "Applied target ${projectType.lockfileName} to $SOURCE_LOCK"`,
    '    elif cmp -s "$SOURCE_LOCK" "$TARGET_LOCK"; then',
    `      echo "Source and target ${projectType.lockfileName} already match"`,
    '    else',
    '      mkdir -p "$STAGE_DIR/.llm_context_target"',
    `      cp "$TARGET_LOCK" "$STAGE_DIR/.llm_context_target/${projectType.lockfileName}"`,
    `      echo "Saved differing target ${projectType.lockfileName} to $STAGE_DIR/.llm_context_target/${projectType.lockfileName}"`,
    '    fi',
    '  fi',
    'fi',
    '',
    'if [[ -f "$DEPENDENCY_TAR" ]]; then',
    '  if [[ "$USED_PREASSEMBLED_REPO" == "1" && "$PREASSEMBLED_REPO_EMBEDS_DEPENDENCIES" == "1" ]]; then',
    `    echo "Preassembled repository already contains ${projectType.dependencyDirectory}; skipping dependency extraction."`,
    '  else',
    '    echo "Extracting target dependencies into staged output for $OUT_DIR"',
    '    tar -xzf "$DEPENDENCY_TAR" -C "$STAGE_DIR"',
    '  fi',
    'else',
    `  echo "No target dependency archive present for $TARGET_KEY; skipping ${projectType.dependencyDirectory} extraction."`,
    'fi',
    '',
    'if [[ -e "$OUT_DIR" ]]; then',
    '  BACKUP_ROOT="$(mktemp -d "$OUT_DIR_PARENT/.llm-context-backup-XXXXXX")"',
    '  BACKUP_PATH="$BACKUP_ROOT/original"',
    '  mv "$OUT_DIR" "$BACKUP_PATH"',
    'fi',
    'mv "$STAGE_DIR" "$OUT_DIR"',
    'if [[ -n "$STAGE_ROOT" && -e "$STAGE_ROOT" ]]; then',
    '  rm -rf "$STAGE_ROOT"',
    '  STAGE_ROOT=""',
    'fi',
    'if [[ -n "$BACKUP_ROOT" && -e "$BACKUP_ROOT" ]]; then',
    '  rm -rf "$BACKUP_ROOT"',
    '  BACKUP_ROOT=""',
    '  BACKUP_PATH=""',
    'fi',
    '',
    'echo',
    "printf 'Repository assembled at: %s\\n' \"$OUT_DIR\"",
    "printf 'Next commands:\\n'",
    "printf '  cd %q\\n' \"$OUT_DIR\"",
    ...buildExtraAssembleCommandLines(projectType),
    ''
  ].filter(Boolean).join('\n');

  const verifyScript = projectType.id === 'npm' ? buildNpmVerifyScript() : buildPythonUvVerifyScript();

  const assembleScriptPath = path.join(bundleDir, 'assemble.offline.sh');
  const verifyScriptPath = path.join(bundleDir, 'verify.offline.sh');

  await fs.writeFile(assembleScriptPath, assembleScript, 'utf8');
  await fs.writeFile(verifyScriptPath, verifyScript, 'utf8');
  await fs.chmod(assembleScriptPath, 0o755);
  await fs.chmod(verifyScriptPath, 0o755);

  return {
    assembleScriptPath,
    verifyScriptPath
  };
}

function buildExtraAssembleCommandLines(projectType) {
  const baseLines = [
    "printf '  %q %q\\n' \"$ROOT_DIR/verify.offline.sh\" \"$OUT_DIR\""
  ];

  if (projectType.id === 'npm') {
    return [
      ...baseLines,
      "printf '  npm run lint\\n'",
      "printf '  npm run test\\n'"
    ];
  }
  return baseLines;
}

function buildNpmVerifyScript() {
  return [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    'ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
    'REPO_DIR="${1:-$ROOT_DIR/repo}"',
    '',
    'if [[ ! -d "$REPO_DIR" ]]; then',
    '  echo "Repository directory does not exist: $REPO_DIR" >&2',
    '  exit 1',
    'fi',
    '',
    'REPO_DIR="$(cd "$REPO_DIR" && pwd)"',
    'RESULT_DIR="$REPO_DIR/.llm_context_verify"',
    '',
    'if [[ ! -f "$REPO_DIR/package.json" ]]; then',
    '  echo "package.json is missing from: $REPO_DIR" >&2',
    '  exit 1',
    'fi',
    '',
    'command -v node >/dev/null 2>&1 || { echo "node is required" >&2; exit 1; }',
    'command -v npm >/dev/null 2>&1 || { echo "npm is required" >&2; exit 1; }',
    '',
    'mkdir -p "$RESULT_DIR"',
    'cd "$REPO_DIR"',
    '',
    'echo "Node: $(node -v)"',
    'echo "npm: $(npm -v)"',
    '',
    'has_script() {',
    "  SCRIPT_NAME=\"$1\" node <<'NODE'",
    "const fs = require('node:fs');",
    "const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));",
    'const scriptName = process.env.SCRIPT_NAME;',
    'process.exit(pkg.scripts && Object.prototype.hasOwnProperty.call(pkg.scripts, scriptName) ? 0 : 1);',
    'NODE',
    '}',
    '',
    'looks_like_jest() {',
    "  node <<'NODE'",
    "const fs = require('node:fs');",
    "const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));",
    "const deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };",
    "const testScript = String(pkg?.scripts?.test || '');",
    "const looksLikeJest = /\\bjest\\b/.test(testScript) || Object.prototype.hasOwnProperty.call(deps, 'jest');",
    'process.exit(looksLikeJest ? 0 : 1);',
    'NODE',
    '}',
    '',
    'run_step() {',
    '  local name="$1"',
    '  shift',
    '  local log_file="$RESULT_DIR/$name.log"',
    '  mkdir -p "$(dirname "$log_file")"',
    '  echo "Running: $*"',
    '  set +e',
    '  "$@" 2>&1 | tee "$log_file"',
    '  local status=${PIPESTATUS[0]}',
    '  set -e',
    '  return "$status"',
    '}',
    '',
    'write_results() {',
    '  cat > "$RESULT_DIR/results.json" <<JSON',
    '{',
    '  "lint": "${lint_status}",',
    '  "test": "${test_status}"',
    '}',
    'JSON',
    '}',
    '',
    'lint_status="skipped"',
    'test_status="skipped"',
    '',
    'if has_script lint; then',
    '  if run_step lint npm run lint; then',
    '    lint_status="passed"',
    '  else',
    '    lint_status="failed"',
    '    echo "Lint failed. See $RESULT_DIR/lint.log" >&2',
    '    write_results',
    '    exit 1',
    '  fi',
    'else',
    '  echo "Skipping lint: no npm script named lint"',
    'fi',
    '',
    'if has_script test; then',
    '  if run_step test npm run test; then',
    '    test_status="passed"',
    '  else',
    '    if looks_like_jest; then',
    '      echo "npm run test failed; retrying with --runInBand because the project looks Jest-based."',
    '      if run_step test_inband npm run test -- --runInBand; then',
    '        test_status="passed-inband"',
    '      else',
    '        test_status="failed"',
    '        echo "Tests failed after the in-band retry. See $RESULT_DIR/test.log and $RESULT_DIR/test_inband.log" >&2',
    '        write_results',
    '        exit 1',
    '      fi',
    '    else',
    '      test_status="failed"',
    '      echo "Tests failed. See $RESULT_DIR/test.log" >&2',
    '      write_results',
    '      exit 1',
    '    fi',
    '  fi',
    'else',
    '  echo "Skipping test: no npm script named test"',
    'fi',
    '',
    'write_results',
    'echo "Wrote $RESULT_DIR/results.json"',
    ''
  ].join('\n');
}

function buildPythonUvVerifyScript() {
  return [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    'ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"',
    'REPO_DIR="${1:-$ROOT_DIR/repo}"',
    '',
    'if [[ ! -d "$REPO_DIR" ]]; then',
    '  echo "Repository directory does not exist: $REPO_DIR" >&2',
    '  exit 1',
    'fi',
    '',
    'REPO_DIR="$(cd "$REPO_DIR" && pwd)"',
    'RESULT_DIR="$REPO_DIR/.llm_context_verify"',
    '',
    'if [[ ! -f "$REPO_DIR/pyproject.toml" ]]; then',
    '  echo "pyproject.toml is missing from: $REPO_DIR" >&2',
    '  exit 1',
    'fi',
    '',
    'if [[ -x "$REPO_DIR/.venv/bin/python" ]]; then',
    '  PYTHON_BIN="$REPO_DIR/.venv/bin/python"',
    'elif command -v python3 >/dev/null 2>&1; then',
    '  PYTHON_BIN="$(command -v python3)"',
    'elif command -v python >/dev/null 2>&1; then',
    '  PYTHON_BIN="$(command -v python)"',
    'else',
    '  echo "python3 or python is required" >&2',
    '  exit 1',
    'fi',
    '',
    'if [[ -d "$REPO_DIR/.venv/bin" ]]; then',
    '  export PATH="$REPO_DIR/.venv/bin:$PATH"',
    'fi',
    '',
    'prepend_pythonpath() {',
    '  local value="$1"',
    '  if [[ -z "$value" ]]; then',
    '    return 0',
    '  fi',
    '  if [[ -n "${PYTHONPATH:-}" ]]; then',
    '    export PYTHONPATH="$value:$PYTHONPATH"',
    '  else',
    '    export PYTHONPATH="$value"',
    '  fi',
    '}',
    '',
    'prepend_pythonpath "$REPO_DIR"',
    'if [[ -d "$REPO_DIR/src" ]]; then',
    '  prepend_pythonpath "$REPO_DIR/src"',
    'fi',
    '',
    'mkdir -p "$RESULT_DIR"',
    'cd "$REPO_DIR"',
    '',
    'echo "Python: $($PYTHON_BIN --version 2>&1)"',
    '',
    'has_module() {',
    '  local module_name="$1"',
    '  MODULE_NAME="$module_name" "$PYTHON_BIN" <<"PY"',
    'import importlib.util',
    'import os',
    'import sys',
    'module_name = os.environ["MODULE_NAME"]',
    'sys.exit(0 if importlib.util.find_spec(module_name) is not None else 1)',
    'PY',
    '}',
    '',
    'run_step() {',
    '  local name="$1"',
    '  shift',
    '  local log_file="$RESULT_DIR/$name.log"',
    '  mkdir -p "$(dirname "$log_file")"',
    '  echo "Running: $*"',
    '  set +e',
    '  "$@" 2>&1 | tee "$log_file"',
    '  local status=${PIPESTATUS[0]}',
    '  set -e',
    '  return "$status"',
    '}',
    '',
    'write_results() {',
    '  cat > "$RESULT_DIR/results.json" <<JSON',
    '{',
    '  "lint": "${lint_status}",',
    '  "test": "${test_status}"',
    '}',
    'JSON',
    '}',
    '',
    'lint_status="skipped"',
    'test_status="skipped"',
    '',
    'if has_module ruff; then',
    '  if run_step lint "$PYTHON_BIN" -m ruff check .; then',
    '    lint_status="passed"',
    '  else',
    '    lint_status="failed"',
    '    echo "Lint failed. See $RESULT_DIR/lint.log" >&2',
    '    write_results',
    '    exit 1',
    '  fi',
    'elif has_module flake8; then',
    '  if run_step lint "$PYTHON_BIN" -m flake8 .; then',
    '    lint_status="passed"',
    '  else',
    '    lint_status="failed"',
    '    echo "Lint failed. See $RESULT_DIR/lint.log" >&2',
    '    write_results',
    '    exit 1',
    '  fi',
    'else',
    '  echo "Skipping lint: no supported Python linter found in the bundled environment"',
    'fi',
    '',
    'if has_module pytest; then',
    '  if run_step test "$PYTHON_BIN" -m pytest; then',
    '    test_status="passed"',
    '  else',
    '    test_status="failed"',
    '    echo "Tests failed. See $RESULT_DIR/test.log" >&2',
    '    write_results',
    '    exit 1',
    '  fi',
    'elif [[ -d tests ]]; then',
    '  if run_step test "$PYTHON_BIN" -m unittest discover -s tests; then',
    '    test_status="passed"',
    '  else',
    '    test_status="failed"',
    '    echo "Tests failed. See $RESULT_DIR/test.log" >&2',
    '    write_results',
    '    exit 1',
    '  fi',
    'elif [[ -d test ]]; then',
    '  if run_step test "$PYTHON_BIN" -m unittest discover -s test; then',
    '    test_status="passed"',
    '  else',
    '    test_status="failed"',
    '    echo "Tests failed. See $RESULT_DIR/test.log" >&2',
    '    write_results',
    '    exit 1',
    '  fi',
    'else',
    '  echo "Skipping test: no pytest installation and no tests/ or test/ directory"',
    'fi',
    '',
    'write_results',
    'echo "Wrote $RESULT_DIR/results.json"',
    ''
  ].join('\n');
}
